"""Media domain models."""

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, ForeignKey, Index, Integer, Text, func, text
from sqlalchemy.orm import Mapped, mapped_column

from acme.core.db import Base, constrained
from acme.core.ids import new_id
from acme.core.storage import UploadPurpose


class Upload(Base):
    """An upload, recorded BEFORE the bytes exist.

    The client asks for a URL, we record the intent, and the client uploads
    directly to storage. `confirmed_at` closes that gap: a row without it is an
    upload that was requested and possibly abandoned, and the sweep deletes
    both the row and any orphaned object.
    """

    __tablename__ = "uploads"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=new_id)
    user_id: Mapped[UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    purpose: Mapped[UploadPurpose] = mapped_column(constrained(UploadPurpose))
    # Generated by us, never supplied by the client: a client-chosen key is a
    # path traversal and an overwrite of someone else's avatar.
    storage_key: Mapped[str] = mapped_column(Text)
    content_type: Mapped[str] = mapped_column(Text)
    size_bytes: Mapped[int | None] = mapped_column(Integer)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        Index("uploads_storage_key_idx", "storage_key", unique=True),
        Index(
            "uploads_unconfirmed_idx",
            "created_at",
            postgresql_where=text("confirmed_at IS NULL"),
        ),
    )
