/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/billing/unprocessed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unprocessed Billing Events
         * @description Deliveries recorded but never completed.
         *
         *     Without this the only symptom of a failed handler is a customer who paid
         *     and has no access, reported by them rather than noticed by us.
         */
        get: operations["unprocessed_billing_events_v1_admin_billing_unprocessed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cards/{card_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend Card
         * @description Suspend a card and revoke its tokens (runbooks/abuse-takedown.md).
         *
         *     Existing CONNECTIONS are untouched. The snapshot is the counterpart's
         *     record of a meeting that happened (ADR-0004), and destroying it would
         *     punish someone who did nothing.
         *
         *     Err toward suspension on the UGC domain: wrongly suspending one card is a
         *     support conversation, while a Safe Browsing listing takes down every link
         *     in the product.
         */
        post: operations["suspend_card_v1_admin_cards__card_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/entitlements/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Entitlement
         * @description Comp an entitlement. Same mechanism as paid, no special-case code.
         *
         *     source='manual' with an expiry, so it resolves through the ordinary path
         *     and expires on its own rather than needing anyone to remember.
         */
        post: operations["grant_entitlement_v1_admin_entitlements_grant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Open Reports
         * @description The moderation queue.
         *
         *     Reports survive the thing they are about - subject FKs are SET NULL, not
         *     CASCADE - so purging a suspended card does not erase the record of why it
         *     was suspended.
         */
        get: operations["open_reports_v1_admin_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports/{report_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Report */
        post: operations["resolve_report_v1_admin_reports__report_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Users
         * @description Look up an account for support.
         *
         *     Emails are masked in the list. The lookup itself is audited: reading who
         *     exists is an access, not a neutral act.
         */
        get: operations["find_users_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_v1_cards_get"];
        put?: never;
        /** Create Card */
        post: operations["create_card_v1_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/public/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Card
         * @description The link-in-bio page. Public, guessable and indexable by design.
         *
         *     Distinct from /scan/{token}, which is non-guessable and noindex. Same card,
         *     two access paths with different exposure (ADR-0008).
         */
        get: operations["public_card_v1_cards_public__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_v1_cards__card_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Card
         * @description Soft delete. Connections keep their card snapshots (ADR-0004).
         */
        delete: operations["delete_card_v1_cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card */
        patch: operations["update_card_v1_cards__card_id__patch"];
        trace?: never;
    };
    "/v1/cards/{card_id}/tokens/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint Live Token
         * @description Short-lived token producing a SYMMETRIC exchange.
         *
         *     The mobile app calls this when the QR screen opens and refreshes on
         *     foreground. Never export the result: presenting it in-app is what makes
         *     symmetric exchange consensual.
         */
        post: operations["mint_live_token_v1_cards__card_id__tokens_live_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}/tokens/static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Static Token
         * @description The card's ONE-WAY token, for badges, exports, NFC and Wallet.
         *
         *     Idempotent: returns the existing token rather than issuing a new one, so
         *     fetching it does not invalidate what is already printed.
         */
        get: operations["get_static_token_v1_cards__card_id__tokens_static_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/{card_id}/tokens/static/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate Static Token
         * @description Kill the current static token and issue a new one.
         *
         *     The remedy when a badge photograph leaks. Everything already printed stops
         *     resolving, which is the point.
         */
        post: operations["rotate_static_token_v1_cards__card_id__tokens_static_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connections
         * @description The contact list. NEVER gated.
         *
         *     Connection history is free forever (00-context/pricing.md): hiding contacts
         *     someone already made reads as theft. Export, analytics and the reminder cap
         *     are the paid surfaces.
         *
         *     Cursor-paginated, never offset - offset skips and duplicates rows as new
         *     connections are inserted, and this table only grows.
         */
        get: operations["list_connections_v1_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Duplicates
         * @description Groups of views with the same counterpart.
         *
         *     Surfaced rather than merged automatically: meeting someone at two events is
         *     legitimately two records until the user says otherwise.
         */
        get: operations["find_duplicates_v1_connections_duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connections/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_v1_connections__view_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Connection
         * @description Remove the caller's copy.
         *
         *     Asymmetric by design: the edge survives until both participants delete
         *     their view. My removing a contact must not erase your record of the same
         *     meeting.
         */
        delete: operations["delete_connection_v1_connections__view_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Connection
         * @description Notes, tags, reminders and archiving.
         *
         *     All of it lands on the caller's own view. The counterpart never sees any of
         *     it, which is the structural guarantee rather than a filtering decision.
         */
        patch: operations["update_connection_v1_connections__view_id__patch"];
        trace?: never;
    };
    "/v1/connections/{view_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Connections
         * @description Fold duplicates into one contact.
         *
         *     Only the caller's VIEWS merge. The edges stay, because each records a real
         *     meeting that happened, and notes are concatenated rather than discarded.
         */
        post: operations["merge_connections_v1_connections__view_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Event
         * @description Join by code.
         *
         *     Rejoining is not an error: someone who taps twice, or who left and came
         *     back, gets the same result.
         */
        post: operations["join_event_v1_events_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Roster
         * @description Upload the registration list.
         *
         *     Gives the dashboard a denominator, which is what turns "400 connections"
         *     into "78% of your attendees connected" - the number organizers are actually
         *     asked about.
         */
        post: operations["import_roster_v1_events__event_id__roster_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Stats
         * @description AGGREGATES ONLY (ADR-0012).
         *
         *     No field here reveals which attendee connected with which - that is
         *     third-party disclosure of relationship data neither party consented to.
         *     Suppressed entirely below a cohort of 10, because on a small event any
         *     aggregate identifies individuals however it is phrased.
         */
        get: operations["event_stats_v1_events__event_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Stream
         * @description Live aggregate counts.
         *
         *     Authorization happens ONCE, before the stream opens - an open connection
         *     cannot be re-checked, so a revoked staff member keeps the stream until they
         *     disconnect. Acceptable because the payload is aggregates only, and it is
         *     documented rather than assumed.
         *
         *     Payload is a full SNAPSHOT, never a delta. That makes a dropped message
         *     self-correcting: reconnect and you have the truth, with no replay log to
         *     maintain.
         *
         *     AGGREGATES ONLY (ADR-0012) - nothing here reveals which attendee connected
         *     with which, and everything is suppressed below a cohort of 10.
         */
        get: operations["event_stream_v1_events__event_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Exchange
         * @description Record an exchange.
         *
         *     Idempotent at two levels, and both are needed. `Idempotency-Key` is handled
         *     by middleware and short-circuits an identical retry before this runs; the
         *     unique index on (pair, event) catches the same meeting submitted twice with
         *     DIFFERENT keys, which is two devices syncing the same offline queue.
         *
         *     Neither alone is enough: the header cannot span devices, and the index
         *     cannot stop a duplicate card creation.
         *
         *     Offline retry makes duplicates the NORMAL case, not an edge case
         *     (ADR-0016), so a repeat returns the original result rather than an error.
         *
         *     Symmetric or one-way is decided by the TOKEN TYPE, never by the request
         *     (ADR-0002).
         */
        post: operations["create_exchange_v1_exchanges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organization_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Event
         * @description Create an event.
         *
         *     The creator becomes owner staff, without which the person who made the
         *     event could not open its dashboard.
         */
        post: operations["create_event_v1_organizations__organization_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/privacy/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete My Account
         * @description Delete this account. In-app, no support contact, no dark patterns.
         *
         *     Immediate: the account is disabled, tokens are revoked, public pages 404.
         *     After the grace period the purge job hard-deletes the profile row, which is
         *     what makes erasure real - soft delete alone is a claim we would not be
         *     keeping.
         *
         *     The `users` anchor survives so counterparties keep their record of a
         *     meeting that happened. That position is disclosed in the privacy policy.
         */
        delete: operations["delete_my_account_v1_privacy_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/privacy/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export My Data
         * @description GDPR Article 20. ALWAYS FREE.
         *
         *     CONNECTION_EXPORT_NOT_ENTITLED must never be returned here. The paid
         *     workflow export is a different endpoint with a different name in the UI,
         *     because gating a legal right behind a subscription is how a support ticket
         *     becomes a regulatory one (ADR-0020).
         */
        get: operations["export_my_data_v1_privacy_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan/{scan_id}/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Interaction
         * @description What the scanner did with the card.
         *
         *     Views are vanity, but "conversion" is broader than a vCard save: tapping
         *     the phone number, opening a LinkedIn link or copying an email are all real
         *     engagement. The client fires this on tel:/mailto:/link taps, on the browser
         *     `copy` event, and on save and Wallet-add.
         *
         *     Idempotent per (scan, kind, target) - clients retry, and a double-tap must
         *     not double-count a conversion.
         *
         *     Screenshots are undetectable, so every figure built on this is a LOWER
         *     BOUND. Say "at least" wherever it surfaces.
         */
        post: operations["record_interaction_v1_scan__scan_id__interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan/{scan_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave Details
         * @description Optionally leave your own details back.
         *
         *     OPTIONAL is the point: requiring this before the vCard download would kill
         *     the save flow, which is the one thing this page must get right.
         *
         *     Creates a pending request the card owner sees immediately, and an
         *     invitation to claim once the sender installs.
         */
        post: operations["leave_details_v1_scan__scan_id__reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Scan
         * @description Resolve a scanned token. NO AUTHENTICATION, deliberately.
         *
         *     Most scanners have no account, and that is the growth loop rather than an
         *     edge case (ADR-0008). This is the highest-traffic endpoint in the product.
         *
         *     Returns the public projection only - never the internal card id, which
         *     would leak a creation timestamp.
         */
        get: operations["resolve_scan_v1_scan__token__get"];
        put?: never;
        /**
         * Record Scan
         * @description Resolve a scanned token and count the scan.
         *
         *     No authentication: most scanners have no account, and that is the growth
         *     loop rather than an edge case (ADR-0008).
         *
         *     Rate limiting FAILS OPEN. If the limiter is unavailable the scan proceeds,
         *     because a live event is exactly when the limiter is most loaded and least
         *     worth trusting.
         */
        post: operations["record_scan_v1_scan__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple Webhook
         * @description Apple App Store Server Notifications V2.
         *
         *     The body is a signed JWS whose certificate chain roots in Apple's CA.
         *     Signature verification needs that chain and is done in the service layer;
         *     this route handles envelope and idempotency.
         */
        post: operations["apple_webhook_v1_webhooks_apple_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/google-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Play Webhook
         * @description Google Play Real-Time Developer Notifications, via Pub/Sub push.
         *
         *     NOT deferred behind Apple and Stripe: if Android ships at launch then Play
         *     billing ships at launch, and an Android subscriber with no entitlements has
         *     paid for nothing.
         *
         *     There is NO signature over the body. The OIDC bearer token is the only
         *     thing authenticating this request, so an endpoint that skips verifying it
         *     is a public subscription grant that behaves exactly like a working one.
         *
         *     The notification is base64 inside `message.data`, so a handler written
         *     against Apple's flat shape sees an empty payload and processes nothing.
         */
        post: operations["google_play_webhook_v1_webhooks_google_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Stripe: HMAC over `timestamp.body`.
         *
         *     The signature covers the payload, so a valid signature cannot be replayed
         *     onto a different body - which is exactly how someone would grant themselves
         *     a plan.
         */
        post: operations["stripe_webhook_v1_webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardCreate */
        CardCreate: {
            /** Company */
            company?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: string;
            }[];
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
            /** Headline */
            headline?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** @default personal */
            kind: components["schemas"]["CardKind"];
            /** Links */
            links?: components["schemas"]["CardLink"][];
            /** Phone */
            phone?: string | null;
            /** Photo Path */
            photo_path?: string | null;
            /** Qr Style */
            qr_style?: {
                [key: string]: string;
            };
            /** Slug */
            slug?: string | null;
            /** Socials */
            socials?: {
                [key: string]: string;
            };
            /** Theme */
            theme?: {
                [key: string]: string;
            };
            /** Website */
            website?: string | null;
        };
        /**
         * CardKind
         * @enum {string}
         */
        CardKind: "personal" | "business" | "custom";
        /**
         * CardLink
         * @description One custom link.
         *
         *     `label` is stored, never derived. Auto-titling would mean fetching
         *     arbitrary user-supplied URLs server-side, which is an SSRF vector for a
         *     cosmetic gain.
         */
        CardLink: {
            /** Label */
            label: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** CardOut */
        CardOut: {
            /** Company */
            company: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Custom Fields */
            custom_fields: {
                [key: string]: string;
            }[];
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Headline */
            headline: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Default */
            is_default: boolean;
            kind: components["schemas"]["CardKind"];
            /** Links */
            links: components["schemas"]["CardLink"][];
            /** Phone */
            phone: string | null;
            /** Photo Path */
            photo_path: string | null;
            /** Qr Style */
            qr_style: {
                [key: string]: string;
            };
            /** Slug */
            slug: string | null;
            /** Socials */
            socials: {
                [key: string]: string;
            };
            /** Theme */
            theme: {
                [key: string]: string;
            };
            /** Theme Version */
            theme_version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Website */
            website: string | null;
        };
        /**
         * CardUpdate
         * @description Every field optional: a PATCH must not require resending the card.
         *
         *     `None` and "absent" are different here. Absent means leave it alone;
         *     explicit null means clear it. Pydantic's exclude_unset gives us that
         *     distinction, and the service relies on it.
         */
        CardUpdate: {
            /** Company */
            company?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: string;
            }[] | null;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Headline */
            headline?: string | null;
            /** Is Default */
            is_default?: boolean | null;
            kind?: components["schemas"]["CardKind"] | null;
            /** Links */
            links?: components["schemas"]["CardLink"][] | null;
            /** Phone */
            phone?: string | null;
            /** Photo Path */
            photo_path?: string | null;
            /** Qr Style */
            qr_style?: {
                [key: string]: string;
            } | null;
            /** Slug */
            slug?: string | null;
            /** Socials */
            socials?: {
                [key: string]: string;
            } | null;
            /** Theme */
            theme?: {
                [key: string]: string;
            } | null;
            /** Website */
            website?: string | null;
        };
        /**
         * ConnectionListOut
         * @description Cursor-paginated. Never offset.
         *
         *     Offset pagination on a growing table skips and duplicates rows as new ones
         *     are inserted, and connections only grow (contracts/api-conventions.md).
         */
        ConnectionListOut: {
            /** Items */
            items: components["schemas"]["ConnectionOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ConnectionOut
         * @description One row in the connection list.
         *
         *     Carries the caller's OWN note and tags. The counterpart's are never
         *     included and are not reachable from here - they live in a different row
         *     with a different owner.
         */
        ConnectionOut: {
            /** Archived At */
            archived_at: string | null;
            channel: components["schemas"]["ScanChannel"];
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            counterpart: components["schemas"]["CounterpartCard"];
            /**
             * Counterpart Changed
             * @description True when the counterpart's live card differs from the snapshot taken at exchange time.
             * @default false
             */
            counterpart_changed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Id */
            event_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Merged Into Id */
            merged_into_id: string | null;
            /** Note */
            note: string | null;
            /**
             * Note Conflict
             * @description Both texts, preserved when two devices edited the note offline. Never silently overwritten (ADR-0016).
             */
            note_conflict?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reminder At */
            reminder_at: string | null;
            /** Reminder Done At */
            reminder_done_at: string | null;
            state: components["schemas"]["ConnectionState"];
            /** Tags */
            tags: string[];
        };
        /**
         * ConnectionState
         * @enum {string}
         */
        ConnectionState: "pending" | "confirmed" | "declined";
        /**
         * ConnectionUpdate
         * @description Every field optional. Absent means leave alone; null means clear.
         */
        ConnectionUpdate: {
            /** Archived */
            archived?: boolean | null;
            /** Note */
            note?: string | null;
            /** Reminder At */
            reminder_at?: string | null;
            /**
             * Resolve Note Conflict
             * @default false
             */
            resolve_note_conflict: boolean;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * CounterpartCard
         * @description The other person, as they were AT THE TIME (ADR-0004).
         *
         *     Rendered from the snapshot, not from their live card. The client shows the
         *     live version with a "details changed since you met" affordance and reveals
         *     this on request.
         */
        CounterpartCard: {
            /** Company */
            company?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Headline */
            headline?: string | null;
            /** Phone */
            phone?: string | null;
            /** Photo Path */
            photo_path?: string | null;
            /** Socials */
            socials?: {
                [key: string]: string;
            };
            /** Website */
            website?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** EventCreate */
        EventCreate: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Leaderboard Enabled
             * @default false
             */
            leaderboard_enabled: boolean;
            /** Name */
            name: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Timezone */
            timezone: string;
            /** Venue */
            venue?: string | null;
            /** @default unlisted */
            visibility: components["schemas"]["EventVisibility"];
        };
        /** EventOut */
        EventOut: {
            /** Code */
            code: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Leaderboard Enabled */
            leaderboard_enabled: boolean;
            /** Name */
            name: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Slug */
            slug: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Timezone */
            timezone: string;
            /** Venue */
            venue: string | null;
            visibility: components["schemas"]["EventVisibility"];
        };
        /**
         * EventStatsOut
         * @description AGGREGATES ONLY (ADR-0012).
         *
         *     No field here may reveal which attendee connected with which. That is
         *     third-party disclosure of relationship data neither party consented to, and
         *     every aggregate is suppressed below a cohort of 10 because "2 of 3
         *     connected" identifies people.
         */
        EventStatsOut: {
            /** Anonymous Scans */
            anonymous_scans: number;
            /** Attendees */
            attendees: number;
            /** Connected Percentage */
            connected_percentage: number | null;
            /** Connections */
            connections: number;
            /**
             * Suppressed
             * @description True when the cohort is too small to report safely.
             * @default false
             */
            suppressed: boolean;
            /** Unique Connectors */
            unique_connectors: number;
        };
        /**
         * EventVisibility
         * @description Three levels, deliberately (ADR-0008).
         *
         *     PUBLIC requires organizer verification, which is both the SEO gate and the
         *     anti-spam filter: nobody pays to host a phishing page.
         * @enum {string}
         */
        EventVisibility: "private" | "unlisted" | "public";
        /** ExchangeRequest */
        ExchangeRequest: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** @default qr_live */
            channel: components["schemas"]["ScanChannel"];
            /** Event Id */
            event_id?: string | null;
            /** Note */
            note?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Token */
            token: string;
        };
        /**
         * ExchangeResult
         * @description What the scanner gets back.
         *
         *     `symmetric` tells the client whether the other party received their card
         *     too. It is derived from the TOKEN TYPE, not requested: a static token never
         *     produces a symmetric exchange, however the client asks.
         */
        ExchangeResult: {
            card: components["schemas"]["PublicCardOut"];
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            state: components["schemas"]["ConnectionState"];
            /** Symmetric */
            symmetric: boolean;
        };
        /**
         * GrantRequest
         * @description Comped pilot partners. Same table and resolver as a paid entitlement.
         *
         *     An expiry is REQUIRED. A permanently comped organizer is how the entire
         *     meetup segment ends up never paying (00-context/pricing.md).
         */
        GrantRequest: {
            /** Entitlement Key */
            entitlement_key: string;
            /** Expires At */
            expires_at: string;
            /** Reason */
            reason: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            subject_kind: components["schemas"]["SubjectKind"];
            /** Value Bool */
            value_bool?: boolean | null;
            /** Value Int */
            value_int?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InteractionKind
         * @description What a scanner did with a card.
         *
         *     Ordered loosely by strength of signal. VCARD_SAVE and WALLET_ADD mean the
         *     contact is kept; the rest mean they acted on it, which is weaker but real -
         *     and treating those as non-conversions is what the two old booleans got
         *     wrong.
         * @enum {string}
         */
        InteractionKind: "vcard_save" | "wallet_add" | "link_click" | "copy" | "call" | "email";
        /** InteractionRequest */
        InteractionRequest: {
            kind: components["schemas"]["InteractionKind"];
            /** Target */
            target?: string | null;
        };
        /** JoinRequest */
        JoinRequest: {
            /** Card Id */
            card_id?: string | null;
            /** Code */
            code: string;
        };
        /**
         * MergeRequest
         * @description Fold one connection view into another.
         *
         *     Meeting the same person at three events is one contact with three event
         *     tags, not three contacts. The EDGES stay - each records a real meeting -
         *     and only the caller's own views are merged.
         */
        MergeRequest: {
            /** Source Ids */
            source_ids: string[];
        };
        /**
         * PublicCardOut
         * @description What a STRANGER sees. Deliberately narrower than CardOut.
         *
         *     No internal id: a UUIDv7 leaks its creation timestamp, and public surfaces
         *     must never expose one (ADR-0010). No theme_version, no is_default - those
         *     are ours, not theirs.
         */
        PublicCardOut: {
            /** Company */
            company: string | null;
            /** Custom Fields */
            custom_fields: {
                [key: string]: string;
            }[];
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Headline */
            headline: string | null;
            /** Links */
            links: components["schemas"]["CardLink"][];
            /** Phone */
            phone: string | null;
            /** Photo Path */
            photo_path: string | null;
            /** Socials */
            socials: {
                [key: string]: string;
            };
            /** Theme */
            theme: {
                [key: string]: string;
            };
            /** Website */
            website: string | null;
        };
        /** ReplyRequest */
        ReplyRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Payload */
            payload?: {
                [key: string]: string;
            };
            /**
             * Website
             * @default
             */
            website: string;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "open" | "actioned" | "dismissed";
        /** RosterEntry */
        RosterEntry: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
        };
        /** RosterImport */
        RosterImport: {
            /** Entries */
            entries: components["schemas"]["RosterEntry"][];
        };
        /** RosterImportResult */
        RosterImportResult: {
            /** Added */
            added: number;
            /** Skipped */
            skipped: number;
        };
        /**
         * ScanChannel
         * @description How an exchange arrived.
         *
         *     Recorded from v1 even though NFC ships in v1.1: retrofitting loses the
         *     attribution history, which is how we learn whether NFC or QR is actually
         *     used.
         * @enum {string}
         */
        ScanChannel: "qr_live" | "qr_static" | "nfc" | "link" | "wallet";
        /** ScanResult */
        ScanResult: {
            card: components["schemas"]["PublicCardOut"];
            /**
             * Scan Id
             * Format: uuid
             */
            scan_id: string;
        };
        /**
         * SubjectKind
         * @enum {string}
         */
        SubjectKind: "user" | "organization";
        /** SuspendRequest */
        SuspendRequest: {
            /**
             * Confirm Id
             * Format: uuid
             */
            confirm_id: string;
            /** Reason */
            reason: string;
        };
        /**
         * TokenKind
         * @description The security model, as a type (ADR-0002).
         *
         *     LIVE produces a symmetric exchange; STATIC never does. Confusing the two is
         *     the harvesting vector the whole design exists to close, so it is worth
         *     having the compiler know the difference.
         * @enum {string}
         */
        TokenKind: "live" | "static";
        /** TokenOut */
        TokenOut: {
            /** Expires At */
            expires_at: string | null;
            kind: components["schemas"]["TokenKind"];
            /** Token */
            token: string;
        };
        /**
         * UserSummary
         * @description TRUNCATED on purpose.
         *
         *     Staff browsing a contact database is exactly the risk this product carries,
         *     so a list view shows enough to identify an account and no more. Full
         *     details need a single-record view, which is audited.
         */
        UserSummary: {
            /** Deleted At */
            deleted_at: string | null;
            /** Display Name */
            display_name: string | null;
            /** Email Masked */
            email_masked: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Purge After */
            purge_after: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookAck
         * @description Providers retry on non-2xx.
         *
         *     A duplicate is expected and harmless - handlers are idempotent against
         *     billing_events - so a repeat is acknowledged rather than errored.
         */
        WebhookAck: {
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /**
             * Received
             * @default true
             */
            received: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    unprocessed_billing_events_v1_admin_billing_unprocessed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    suspend_card_v1_admin_cards__card_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuspendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_entitlement_v1_admin_entitlements_grant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_reports_v1_admin_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    resolve_report_v1_admin_reports__report_id__resolve_post: {
        parameters: {
            query?: {
                outcome?: components["schemas"]["ReportStatus"];
                note?: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_users_v1_admin_users_get: {
        parameters: {
            query?: {
                email?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_v1_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
        };
    };
    create_card_v1_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_card_v1_cards_public__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_v1_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_v1_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_v1_cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_live_token_v1_cards__card_id__tokens_live_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_static_token_v1_cards__card_id__tokens_static_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_static_token_v1_cards__card_id__tokens_static_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_v1_connections_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                event_id?: string | null;
                tag?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_duplicates_v1_connections_duplicates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    get_connection_v1_connections__view_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_v1_connections__view_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_v1_connections__view_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_connections_v1_connections__view_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_event_v1_events_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_roster_v1_events__event_id__roster_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stats_v1_events__event_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_v1_events__event_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exchange_v1_exchanges_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_v1_organizations__organization_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_account_v1_privacy_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    export_my_data_v1_privacy_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    record_interaction_v1_scan__scan_id__interactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_details_v1_scan__scan_id__reply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_scan_v1_scan__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_scan_v1_scan__token__post: {
        parameters: {
            query?: {
                channel?: components["schemas"]["ScanChannel"];
                event_id?: string | null;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apple_webhook_v1_webhooks_apple_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
        };
    };
    google_play_webhook_v1_webhooks_google_play_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_v1_webhooks_stripe_post: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
